mysql:
  containter_name: mattermost-mysql
  ports:
    - "3306:3306"
  image: "mysql:5.7"
  restart: always
  environment:
    MYSQL_ROOT_HOST: "%"
    MYSQL_ROOT_PASSWORD: mostest
    MYSQL_PASSWORD: mostest
    MYSQL_USER: mmuser
    MYSQL_DATABASE: mattermost_test